[build]
    publish = "public"
    command = "echo No build command"
    node_bundler = "esbuild"
    external_node_modules = ["hud-sdk"]

[dev]
    publish = "public"
    node_bundler = "esbuild"
    external_node_modules = ["hud-sdk"]

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
