[build]
    publish = "public"
    command = "echo No build command"
    node_bundler = "zisi"

[dev]
    publish = "public"
    node_bundler = "zisi"

[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/:splat"
    status = 200
